module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 14,
    fontFamily: 'Fira Code, monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
    borderColor: '#333',
    showHamburgerMenu: '',
    showWindowControls: false,
    padding: '5px 5px 10px 5px',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: '/bin/zsh',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    // Plugin settings
    hyperclean: {
      hideTabs: true, // default: false
    },
    summon: {
      hideDock: false,
      hotkey: 'Alt+Space'
    },
  },
  plugins: [
    'hyper-dracula',
    'hyper-krftwrk',
    'hyperclean',
    'hyperline',
    'hyperterm-summon',
  ],
  localPlugins: [],
  keymaps: {
    'window:devtools': 'cmd+alt+i',
  },
};
