###############################################################################
# tmux.conf @ jesse
################################################################################

# Settings
set -g base-index 1
setw -g pane-base-index 1

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Environment Variables
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

# Options
set-option -g default-shell /bin/zsh
set-option -g allow-rename off

# Reload source
bind r source-file $HOME/.tmux.conf

# Saner pane splitting
bind -n M-| split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes using OPT+HJKL w/o prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Resize panes using OPT+SHIFT+HJKL w/o prefix
bind -n M-S-h resize-pane -L
bind -n M-S-l resize-pane -R
bind -n M-S-k resize-pane -U
bind -n M-S-j resize-pane -D

# Session Switching
bind -n M-Tab switch-client -n
bind -n M-S-Tab switch-client -p

# Init TPM
run '~/.tmux/plugins/tpm/tpm'
