###############################################################################
# tmux.conf @ jesse
################################################################################

# Settings
set -sg escape-time 0
set -g base-index 1

# Environment Variables
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

# Options
set-option -g default-shell /bin/zsh
set-option -g allow-rename off

# Reload source
bind r source-file ~/.tmux.conf

# Saner pane splitting
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes using Alt+HJKL w/o prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Resize panes
bind -n M-S-Left resize-pane -L
bind -n M-S-Right resize-pane -R
bind -n M-S-Up resize-pane -U
bind -n M-S-Down resize-pane -D

# Window Switching
bind -n M-Tab next-window
bind -n M-S-Tab previous-window
